import type { Metadata } from "next";
import { Geist, Geist_Mono, Hanken_Grotesk } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const jetbrainsMono = localFont({
  src: './fonts/JetBrainsMono-Regular.woff2',
  display: 'swap',
  variable: '--font-jetbrains',
})

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.className} ${hankenGrotesk.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}

