import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import CustomCursor from './components/CustomCursor';

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

const jetbrainsMono = localFont({
  src: './fonts/JetBrainsMono-Regular.woff2',
  display: 'swap',
  variable: '--font-jetbrains',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.className} ${bricolageGrotesque.variable} ${geistSans.variable} antialiased`}>
        {children}
        <CustomCursor />
      </body>
    </html>
  )
}

